# Generated by Django 2.0.4 on 2018-05-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=255)),
                ('plot_creation_date', models.DateField(auto_now_add=True)),
                ('plot_last_modification', models.DateTimeField(auto_now_add=True)),
                ('plot_type', models.CharField(choices=[('B', 'Bar'), ('L', 'Linear'), ('S', 'Scatter'), ('P', 'Pie')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_type', models.CharField(choices=[('D', 'DataColumn'), ('G', 'GroupingColumn')], default='D', max_length=1)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Column')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_creation_date', models.DateField(auto_now_add=True)),
                ('report_last_modification', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_caption', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Plot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded_raport_caption', models.CharField(max_length=255)),
                ('element_start', models.IntegerField()),
                ('element_end', models.IntegerField()),
                ('order', models.IntegerField()),
                ('embedded_raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportEmbedded', to='reports.Report')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_caption', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('C', 'Classic'), ('M', 'Modern'), ('O', 'Office'), ('A', 'Alternating')], default='C', max_length=1)),
                ('rows_columns_inverted', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Column')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportElementTable')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_name', models.CharField(max_length=255)),
                ('spreadsheet_description', models.TextField(default='')),
                ('spreadsheet_creation_date', models.DateField(auto_now_add=True)),
                ('spreadsheet_last_modification', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(default=5)),
                ('column_number', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Spreadsheet'),
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='reports.Column'),
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['user'], name='reports_spr_user_id_5f53be_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['spreadsheet'], name='reports_col_spreads_2ff0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['contents'], name='reports_cel_content_3909b2_idx'),
        ),
    ]
