# Generated by Django 2.0.5 on 2018-05-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=255)),
                ('plot_creation_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('plot_last_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('plot_type', models.CharField(choices=[('B', 'Bar'), ('L', 'Linear'), ('S', 'Scatter'), ('P', 'Pie')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DataColumn'), ('G', 'GroupingColumn')], max_length=1)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Column')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_creation_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('report_last_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_caption', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Plot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded_raport_caption', models.CharField(max_length=255)),
                ('element_start', models.IntegerField()),
                ('element_end', models.IntegerField()),
                ('order', models.IntegerField()),
                ('embedded_raport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportEmbedded', to='reports.Report')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_caption', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('C', 'Classic'), ('M', 'Modern'), ('O', 'Office'), ('A', 'Alternating')], max_length=1)),
                ('rows_columns_inverted', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Column')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ReportElementTable')),
            ],
        ),
        migrations.CreateModel(
            name='ReportElementText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_name', models.CharField(max_length=255)),
                ('spreadsheet_creation_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('spreadsheet_last_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('variable_names', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Spreadsheet'),
        ),
    ]
