# Generated by Django 2.0.5 on 2018-05-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='variable_names',
        ),
    ]
