# Generated by Django 2.0.4 on 2018-05-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_plot_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Spreadsheet'),
        ),
    ]
