# Generated by Django 2.0.4 on 2018-05-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180531_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='data_columns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plot',
            name='grouping_columns',
            field=models.TextField(default=''),
        ),
    ]
