# Generated by Django 2.0.5 on 2018-05-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180509_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Spreadsheet'),
        ),
    ]
