# Generated by Django 2.0.4 on 2018-05-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180531_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotdata',
            name='column',
        ),
        migrations.RemoveField(
            model_name='plotdata',
            name='plot',
        ),
        migrations.DeleteModel(
            name='PlotData',
        ),
    ]
