# Generated by Django 2.0.5 on 2018-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20180531_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
