# Generated by Django 2.0.5 on 2018-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20180517_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='contents',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
