# Generated by Django 2.0.5 on 2018-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20180603_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('B', 'Bar'), ('L', 'Linear'), ('P', 'Pie'), ('R', 'Radar'), ('G', 'Gauge'), ('X', 'Box'), ('Y', 'Pyramid')], max_length=1),
        ),
    ]
