# Generated by Django 2.0.4 on 2018-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20180517_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='spreadsheet_description',
            field=models.TextField(default=''),
        ),
    ]
