# Generated by Django 2.0.4 on 2018-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_spreadsheet_spreadsheet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='column_number',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='row_number',
            field=models.IntegerField(default=10),
        ),
    ]
