# Generated by Django 2.0.5 on 2018-06-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20180603_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('element_order', models.IntegerField()),
                ('text', models.TextField()),
                ('caption', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('C', 'Classic'), ('M', 'Modern'), ('O', 'Office'), ('A', 'Alternating')], default='C', max_length=1)),
                ('rows_columns_inverted', models.BooleanField(default=False)),
                ('columns', models.TextField(default='')),
                ('embedded_raport_caption', models.CharField(max_length=255)),
                ('element_start', models.IntegerField()),
                ('element_end', models.IntegerField()),
                ('embedded_raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportEmbedded', to='reports.Report')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Plot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.Report')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportelementplot',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='reportelementplot',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportelementreport',
            name='embedded_raport',
        ),
        migrations.RemoveField(
            model_name='reportelementreport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportelementtable',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportelementtabledata',
            name='column',
        ),
        migrations.RemoveField(
            model_name='reportelementtabledata',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportelementtext',
            name='report',
        ),
        migrations.DeleteModel(
            name='ReportElementPlot',
        ),
        migrations.DeleteModel(
            name='ReportElementReport',
        ),
        migrations.DeleteModel(
            name='ReportElementTable',
        ),
        migrations.DeleteModel(
            name='ReportElementTableData',
        ),
        migrations.DeleteModel(
            name='ReportElementText',
        ),
    ]
