# Generated by Django 2.0.5 on 2018-06-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20180603_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportelement',
            name='embedded_raport_caption',
        ),
        migrations.RemoveField(
            model_name='reportelement',
            name='rows_columns_inverted',
        ),
        migrations.AddField(
            model_name='reportelement',
            name='element_type',
            field=models.CharField(choices=[('X', 'Text Block'), ('T', 'Table'), ('P', 'Plot'), ('R', 'Report')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='reportelement',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Spreadsheet'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('B', 'Bar'), ('L', 'Linear'), ('P', 'Pie'), ('R', 'Radar'), ('X', 'Box'), ('Y', 'Pyramid')], default='B', max_length=1),
        ),
    ]
