# Generated by Django 2.0.5 on 2018-06-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20180603_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='columns',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='embedded_raport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportEmbedded', to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Plot'),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
