# Generated by Django 2.0.5 on 2018-06-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180604_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportElements', to='reports.Report'),
        ),
    ]
