# Generated by Django 2.0.5 on 2018-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20180604_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='element_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='element_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
