# Generated by Django 2.0.5 on 2018-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20180604_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.TextField(default=''),
        ),
    ]
